---
server:
  port: 8080
  contextPath: /UserTest
---
# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: 
    driverClassName: org.h2.Driver
   # schema: schema.sql
   # data: data.sql
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect 
  h2:
    console:
      enabled: true
      path: /h2
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

#---
#spring:
#  profiles: prod
#datasource:
#  sampleapp:
#    url: jdbc:mysql://localhost:3306/websystique
#    username: myuser
#    password: mypassword
#    driverClassName: com.mysql.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
#    hibernate:
#      hbm2ddl.method: update
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect

